version: '3.5'
services:
  rabbitmq:
    image: rabbitmq:3-management
    container_name: startupgo_policy-rabbitmq
    hostname: startupgo_policy-rabbitmq # database unique name
    networks:
      - rabbitmq
    environment:
      - RABBITMQ_DEFAULT_USER=startupgo_policy
      - RABBITMQ_DEFAULT_PASS=startupgo_policy
      - RABBITMQ_ERLANG_COOKIE=startupgo_policyrabbitmqservice
    ports:
      - "15672:15672"
      - "5672:5672"

  flower:
    image: hugoseabra19/docker-celery-flower
    container_name: startupgo_policy-flower
    environment:
      - CELERY_BROKER_URL=amqp://startupgo_policy:startupgo_policy@rabbitmq:5672/
      - FLOWER_PORT=5555
    ports:
      - 5555:5555
    networks:
      - rabbitmq

  mailhog:
    image: blueimp/mailhog
    container_name: startupgo_policy-mailhog
    ports:
      - "1025:1025"
      - "8025:8025"

volumes:
  pgadmin_data:

networks:
  rabbitmq:
    name: local_rabbitmq
